version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: stashr
    ldflags:
      - -s -w -X github.com/harshalranjhani/stashr/internal/version.Version={{.Version}} -X github.com/harshalranjhani/stashr/internal/version.GitCommit={{.Commit}} -X github.com/harshalranjhani/stashr/internal/version.BuildDate={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
    builds_info:
      group: root
      owner: root
    rlcp: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - '^chore:'
            - '^ci:'
            - 'README'
            - Merge pull request
            - Merge branch

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: stashr
    homepage: "https://stashr.harshalranjhani.in"
    repository:
      owner: harshalranjhani
      name: homebrew-harshalranjhani
    commit_author:
      name: harshalranjhani
      email: ranjhaniharshal@gmail.com

checksum:
  name_template: 'checksums.txt'